AWSTemplateFormatVersion: 2010-09-09
Description: Configure the Temporary cross account role.

Parameters:
  AdministratorAccountId:
    Type: String
    Description: AWS Account Id of the Shared Service (the account in which StackSets will be created).
    MaxLength: 12
    MinLength: 12

Resources:
  SSAccountAccessAdmRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SSAccountAccessRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref AdministratorAccountId
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  SSAccountAccesspwrRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SSAccountAccessRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref AdministratorAccountId
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  SSAccountAccessUsrRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SSAccountAccessRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref AdministratorAccountId
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess